#!/usr/bin/env bash

current_zoom=$(hyprctl getoption cursor:zoom_factor | awk '/float:/ {print $2}')

new_zoom=$(awk -v cur="$current_zoom" -v inp="$1" 'BEGIN {
    if (inp ~ /^[+-]/) {
        res = cur + inp
    } else {
        res = inp
    }
    if (res < 1) res = 1
    print res
}')

hyprctl eval "hl.config({ cursor = { zoom_factor = $new_zoom } })"
